version: '3'
services:
  db:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - 5430:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: gallows_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080